# Generated by Django 3.0.8 on 2020-07-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
