version: "3"

services:
  python:
    container_name: python-django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "sh /usr/src/sh/django_run.sh"
    volumes:
      - ./hackathon:/usr/src/app/
      - ./django_run.sh:/usr/src/sh/django_run.sh:ro
